export { Landing } from './Landing'
export { Portfolio } from './Portfolio'
export { About } from './About'
export { Education } from './Education'
export { Experience } from './Experience'
export { Skills } from './Skills'
export { Contact } from './Contact'
